export const resmessage = {
  validation_error: 'validation-error',
  confirm_password_mismatch: 'confirm-password-mismatch',
  login_successful: 'User Login successful!',
  username_email_exists: 'username-email-exists',
  user_added: 'user added successfully!',
  record_added: 'record-added',
  record_updated: 'record-updated',
  record_deleted: 'record-deleted',
  record_exists: 'record-exists',
  record_not_found: 'record-not-found',
  mongodb_validation_err: 'mongodb-validation-error',
  something_wrong: 'something-went-wrong',
  bad_credentials: 'bad-credentials',
  un_authorized_access: 'un-authorized-access',
  user_not_found: 'user-not-found',
  new_password_generated: 'new-password-generated',
  incorrect_password: 'incorrect-password',
  password_changed: 'password-changed',
  profile_pic_uploaded: 'profile-pic-uploaded',
  adver_pic_uploaded: 'adver-pic-uploaded',
  record_can_not_be_deleted: 'record-can-not-be-deleted',
  coin_currency_not_available: 'coin-currency-not-available',
  transaction_successful: 'Transaction Successful!',
  transaction_faliure: 'Transaction failed'
};
